import numpy as np
x = np.array([0.02, -0.01, 0.03])
y = np.array([0.01, -0.02, 0.015])
print("La correlacion es(x, y):", np.corrcoef(x, y)[0] [1])
# para abajo es como se hace este proceso a mano
print("El promedio de x es", x.mean())
print("El promedio de y es:", y.mean())
x_centrada = x - x.mean()
print("Los desvios individuales de x son:", x_centrada)
y_centrada = y - y.mean()
print("Los desvios individuales de y son:", y_centrada)
print("Los desvios multiplicados y sumados de (x, y):", np.dot(x_centrada, y_centrada))
magnitud_x = np.sqrt(np.dot(x_centrada, x_centrada))
print("La magnitud de x es:", magnitud_x)
magnitud_y = np.sqrt(np.dot(y_centrada, y_centrada))
print("La magnitud de y es:", magnitud_y)
numerador = np.dot(x_centrada, y_centrada)
correlacion = numerador / (magnitud_x * magnitud_y)
print("La correalcion(x,y) es:", correlacion)
